# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersinform',
            old_name='number',
            new_name='servis',
        ),
    ]
