# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160418_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersinform',
            name='date',
            field=models.DateTimeField(verbose_name='reqest date'),
        ),
    ]
