# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160419_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersinform',
            name='fio',
            field=models.CharField(default=23, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordersinform',
            name='servis',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ordersinform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInform'),
        ),
    ]
