# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160420_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersinform',
            name='fio',
        ),
    ]
