# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_ordersinform_fio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersinform',
            old_name='user',
            new_name='users',
        ),
    ]
