# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20160421_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersinform',
            old_name='users',
            new_name='user',
        ),
    ]
