# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20160423_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersinform',
            old_name='login',
            new_name='user',
        ),
    ]
