# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160421_1316'),
        ('orders', '0011_remove_ordersinform_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата запроса')),
                ('service', models.TextField(verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInform')),
            ],
        ),
        migrations.DeleteModel(
            name='OrdersInform',
        ),
    ]
