# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('vin', models.CharField(max_length=16)),
                ('number', models.CharField(max_length=8)),
            ],
        ),
    ]
