# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinform_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinform',
            name='phone_number',
            field=models.CharField(default=23, max_length=16),
            preserve_default=False,
        ),
    ]
