# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinform_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinform',
            old_name='user',
            new_name='users',
        ),
    ]
