# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20160421_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinform',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userinform',
            name='number',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='userinform',
            name='phone_number',
            field=models.IntegerField(max_length=16),
        ),
    ]
