# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160421_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinform',
            name='number',
        ),
        migrations.RemoveField(
            model_name='userinform',
            name='phone_number',
        ),
    ]
