# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160423_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinform',
            name='number',
            field=models.CharField(max_length=8),
        ),
    ]
